services:
   db:
    image: mysql:latest
    container_name: db_server
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: unidb
      MYSQL_USER: user1
      MYSQL_PASSWORD: rootpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      retries: 5
      start_period: 5s

   backend:
    container_name: backend
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile to use (you can change the filename if it's named differently)
    ports:
      - "5000:5000"  # Expose port 5000 from the container to the host
    working_dir: /app  # Set the working directory inside the container
    volumes:
      - ./app:/app  # Mount the local ./app directory to /app inside the container
    command: ["python", "app.py"]
    depends_on:
      db:
         condition: service_healthy
